// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LaunchTheGame(arg1:string,arg2:string):Promise<void>;

export function OpenToDir():Promise<void>;
