// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LaunchTheGame(arg1, arg2) {
  return window['go']['app']['App']['LaunchTheGame'](arg1, arg2);
}
